### ISSUE TITLE
Is it a bug in the dataloader?

### ISSUE THREAD

**Issue by LinghaoChan** [tianxintao/Online-Motion-Style-Transfer#4]
Is it a bug in the dataloader? 

When you want to generate the output style, the `if` statement is checking the `input_style`, not 'output_style'.
```
if input_style.sum() == 0.0:
    output_style[np.random.randint(0, len(style_labels))] = 1
```
Refer to:
https://github.com/tianxintao/Online-Motion-Style-Transfer/blob/3f73858355c22949eaf360d0ec9d7349dde6e481/dataloader.py#L74

**Comment by tianxintao** [comment]
Nope, it's not a bug. Basically, what it does is that it sets the output style to one of the none neutral styles if the input style is neutral.

**Comment by LinghaoChan** [comment]
However, the `output_style` vector here is a zero vector. Which kind of style will it transfer to?

**Comment by tianxintao** [comment]
The zero vector refers to neutral style.

**Comment by LinghaoChan** [comment]
OK, I see. Thanks a lot.
